name: krishna
on: push
jobs:
  Green:
    runs-on: ubuntu-latest
    steps:
      - name: Good news
        run: echo "Good news!"
      - name: Bad news
        run:
          echo "Bad news are not update"
          echo "bad news"
  Red:
    runs-on:
    steps:
      - name: Bad news
        run: echo "this is Bad news"